import React, { useState, useEffect } from 'react';
import { StaffProfile, CreateStaffData, UpdateStaffData } from '@/services/staff.service';
import { getAllRoles } from '@/services/role.service';
import Button from '@/components/common/Button';
import DatePicker from '@/components/common/DatePicker';
import { formatDate } from '@/utils/dateUtils';
import { toast } from 'react-toastify';

interface Role {
  id: string;
  name: string;
  description?: string;
}

interface StaffFormProps {
  staff?: StaffProfile;
  onSubmit: (data: any) => void;
  isSubmitting: boolean;
  isEditMode: boolean;
}

const StaffForm: React.FC<StaffFormProps> = ({
  staff,
  onSubmit,
  isSubmitting,
  isEditMode,
}) => {
  const [roles, setRoles] = useState<Role[]>([]);
  const [formData, setFormData] = useState<CreateStaffData | UpdateStaffData>({
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    phone: '',
    address: '',
    dateOfBirth: '',
    joinDate: '',
    department: '',
    position: '',
    status: 'ACTIVE',
    roleIds: [],
  });
  const [loadingRoles, setLoadingRoles] = useState(true);

  useEffect(() => {
    // Fetch roles
    const fetchRoles = async () => {
      try {
        setLoadingRoles(true);
        const data = await getAllRoles();
        setRoles(data);
      } catch (error) {
        console.error('Error fetching roles:', error);
        // Show error in UI instead of using fallback data
        toast.error('Failed to load roles. Please try again.');
      } finally {
        setLoadingRoles(false);
      }
    };

    fetchRoles();

    // If editing, populate form with staff data
    if (isEditMode && staff) {
      console.log('Staff roles:', staff.roles);
      
      // Extract role IDs from the staff object
      // The backend returns roles as an array of objects with a roleId property
      const roleIds = staff.roles.map(role => role.roleId || (role.role && role.role.id));
      console.log('Mapped roleIds:', roleIds);
      
      setFormData({
        employeeId: staff.employeeId,
        firstName: staff.firstName,
        lastName: staff.lastName,
        email: staff.email,
        phone: staff.phone,
        address: staff.address,
        dateOfBirth: staff.dateOfBirth,
        joinDate: staff.joinDate,
        department: staff.department,
        position: staff.position,
        status: staff.status,
        roleIds: roleIds.filter((id): id is string => id !== undefined),
      });
    }
  }, [isEditMode, staff]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleDateChange = (name: string, date: Date | null) => {
    if (date) {
      // Format date as ISO string for backend compatibility
      setFormData(prev => ({ ...prev, [name]: date.toISOString() }));
    }
  };

  const handleRoleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, checked } = e.target;
    console.log('Role change:', { value, checked });
    
    setFormData(prev => {
      // Convert all IDs to strings for consistency
      const currentRoleIds = (prev.roleIds || []).map(id => String(id));
      console.log('Current roleIds:', currentRoleIds);
      
      const roleIdStr = String(value);
      
      let newRoleIds;
      if (checked) {
        // Add the role ID if it's not already in the array
        if (!currentRoleIds.includes(roleIdStr)) {
          newRoleIds = [...currentRoleIds, roleIdStr];
        } else {
          newRoleIds = currentRoleIds;
        }
      } else {
        // Remove the role ID
        newRoleIds = currentRoleIds.filter(id => id !== roleIdStr);
      }
      
      console.log('New roleIds:', newRoleIds);
      return { ...prev, roleIds: newRoleIds };
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Create a copy of the form data
    const submissionData = { ...formData };
    
    // Remove employeeId when creating a new staff member
    // as it will be auto-generated by the backend
    if (!isEditMode && 'employeeId' in submissionData) {
      delete submissionData.employeeId;
    }
    
    // Ensure roleIds is an array of strings
    if (submissionData.roleIds) {
      submissionData.roleIds = submissionData.roleIds.map(id => String(id));
      console.log('Submitting with roleIds:', submissionData.roleIds);
    }
    
    console.log('Submitting staff data:', submissionData);
    onSubmit(submissionData);
  };

  return (
    <form onSubmit={handleSubmit} className="bg-white shadow sm:rounded-lg">
      <div className="px-4 py-5 sm:p-6">
        <div className="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          {/* Employee ID */}
          <div className="sm:col-span-2">
            <label htmlFor="employeeId" className="block text-sm font-medium text-gray-700">
              Employee ID
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="employeeId"
                id="employeeId"
                value={isEditMode ? ((formData as any).employeeId || '') : 'Will be auto-generated'}
                onChange={handleChange}
                disabled={true}
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm disabled:bg-gray-100"
              />
              {!isEditMode && (
                <p className="mt-1 text-xs text-gray-500">
                  Employee ID will be automatically generated upon creation.
                </p>
              )}
            </div>
          </div>

          {/* First Name */}
          <div className="sm:col-span-2">
            <label htmlFor="firstName" className="block text-sm font-medium text-gray-700">
              First Name
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="firstName"
                id="firstName"
                value={formData.firstName || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Last Name */}
          <div className="sm:col-span-2">
            <label htmlFor="lastName" className="block text-sm font-medium text-gray-700">
              Last Name
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="lastName"
                id="lastName"
                value={formData.lastName || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Email */}
          <div className="sm:col-span-3">
            <label htmlFor="email" className="block text-sm font-medium text-gray-700">
              Email
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="email"
                id="email"
                value={formData.email || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Phone */}
          <div className="sm:col-span-3">
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700">
              Phone
            </label>
            <div className="mt-1">
              <input
                type="tel"
                name="phone"
                id="phone"
                value={formData.phone || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Password (only for create mode) */}
          {!isEditMode && (
            <div className="sm:col-span-3">
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Password
              </label>
              <div className="mt-1">
                <input
                  type="password"
                  name="password"
                  id="password"
                  value={(formData as CreateStaffData).password || ''}
                  onChange={handleChange}
                  required
                  minLength={6}
                  className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
                />
              </div>
              <p className="mt-1 text-xs text-gray-500">
                Must be at least 6 characters long.
              </p>
            </div>
          )}

          {/* Address */}
          <div className="sm:col-span-6">
            <label htmlFor="address" className="block text-sm font-medium text-gray-700">
              Address
            </label>
            <div className="mt-1">
              <textarea
                name="address"
                id="address"
                rows={3}
                value={formData.address || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Date of Birth */}
          <div className="sm:col-span-3">
            <label htmlFor="dateOfBirth" className="block text-sm font-medium text-gray-700">
              Date of Birth
            </label>
            <div className="mt-1">
              <DatePicker
                id="dateOfBirth"
                selected={(formData as any).dateOfBirth ? new Date((formData as any).dateOfBirth) : null}
                onChange={(date) => handleDateChange('dateOfBirth', date)}
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Join Date */}
          <div className="sm:col-span-3">
            <label htmlFor="joinDate" className="block text-sm font-medium text-gray-700">
              Join Date
            </label>
            <div className="mt-1">
              <DatePicker
                id="joinDate"
                selected={(formData as any).joinDate ? new Date((formData as any).joinDate) : null}
                onChange={(date) => handleDateChange('joinDate', date)}
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Department */}
          <div className="sm:col-span-3">
            <label htmlFor="department" className="block text-sm font-medium text-gray-700">
              Department
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="department"
                id="department"
                value={formData.department || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Position */}
          <div className="sm:col-span-3">
            <label htmlFor="position" className="block text-sm font-medium text-gray-700">
              Position
            </label>
            <div className="mt-1">
              <input
                type="text"
                name="position"
                id="position"
                value={formData.position || ''}
                onChange={handleChange}
                required
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              />
            </div>
          </div>

          {/* Status */}
          <div className="sm:col-span-3">
            <label htmlFor="status" className="block text-sm font-medium text-gray-700">
              Status
            </label>
            <div className="mt-1">
              <select
                id="status"
                name="status"
                value={formData.status || 'ACTIVE'}
                onChange={handleChange}
                className="block w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 sm:text-sm"
              >
                <option value="ACTIVE">Active</option>
                <option value="INACTIVE">Inactive</option>
                <option value="ON_LEAVE">On Leave</option>
                <option value="TERMINATED">Terminated</option>
              </select>
            </div>
          </div>

          {/* Roles */}
          <div className="sm:col-span-6">
            <fieldset>
              <legend className="text-sm font-medium text-gray-700">Roles</legend>
              <div className="mt-2 space-y-2">
                {loadingRoles ? (
                  <p className="text-sm text-gray-500">Loading roles...</p>
                ) : (
                  roles.map((role) => {
                    // Convert all IDs to strings for comparison
                    const roleIdStr = String(role.id);
                    const formRoleIds = (formData.roleIds || []).map(id => String(id));
                    const isChecked = formRoleIds.includes(roleIdStr);
                    
                    console.log(`Role ${role.name} (${roleIdStr}), checked:`, isChecked);
                    console.log('formData.roleIds:', formRoleIds);
                    return (
                      <div key={role.id} className="relative flex items-start">
                        <div className="flex h-5 items-center">
                          <input
                            id={`role-${role.id}`}
                            name={`role-${role.id}`}
                            type="checkbox"
                            value={role.id}
                            checked={isChecked}
                            onChange={handleRoleChange}
                            className="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                          />
                        </div>
                        <div className="ml-3 text-sm">
                          <label htmlFor={`role-${role.id}`} className="font-medium text-gray-700">
                            {role.name}
                          </label>
                          {role.description && (
                            <p className="text-gray-500">{role.description}</p>
                          )}
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </fieldset>
          </div>
        </div>
      </div>
      <div className="px-4 py-3 bg-gray-50 text-right sm:px-6">
        <Button
          type="submit"
          variant="primary"
          isLoading={isSubmitting}
          disabled={isSubmitting}
        >
          {isEditMode ? 'Update Staff' : 'Create Staff'}
        </Button>
      </div>
    </form>
  );
};

export default StaffForm;