trigger:
  branches:
    include:
      - main
      
  paths:
    include:
      - fe/*
      - be/*

pool:
  name: 'Astro'

variables:
  nodeVersion: '24.x'
  productionPath: '/opt/myagent/_work/1/s/production'
  backupPath: '/opt/myagent/_work/1/s/backups'

stages:
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: BuildFrontendJob
    displayName: 'Build Next.js App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'
    
    - script: |
        cd fe
        npm install
      displayName: 'Install Frontend Dependencies'
    
    - script: |
        cd fe
        npm run type-check
      displayName: 'Run TypeScript Check'
    
    - script: |
        cd fe
        npm run build
      displayName: 'Build Frontend Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'fe'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend_live.tar.gz'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend_live.tar.gz'
        ArtifactName: 'frontend'
        publishLocation: 'Container'

- stage: BuildBackend
  displayName: 'Build Backend'
  jobs:
  - job: BuildBackendJob
    displayName: 'Build Node.js API'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'
    
    - script: |
        cd be
        npm install
      displayName: 'Install Backend Dependencies'

    - script: |
        cd be
        npm run prisma:generate
      displayName: 'Generate Prisma Client'
    
    - script: |
        cd be
        npm run build
      displayName: 'Build Backend Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'be'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend_live.tar.gz'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend_live.tar.gz'
        ArtifactName: 'backend'
        publishLocation: 'Container'

- stage: PreDeploy
  displayName: 'Pre-Deployment Setup'
  dependsOn: 
    - BuildFrontend
    - BuildBackend
  condition: and(succeeded('BuildFrontend'), succeeded('BuildBackend'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: PreDeployJob
    displayName: 'Prepare Production Environment'
    steps:
    - script: |
        # Ensure production directories exist
        mkdir -p $(productionPath)
        mkdir -p $(backupPath)
        echo "Production and backup directories prepared"
      displayName: 'Setup Base Directories'

    - script: |
        # Create backup directories with timestamp
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        mkdir -p $(backupPath)/$TIMESTAMP
        echo "Created backup directory: $(backupPath)/$TIMESTAMP"
        echo "##vso[task.setvariable variable=deployTimestamp]$TIMESTAMP"
      displayName: 'Create Backup Directory'

    - script: |
        # Backup current production if it exists
        TIMESTAMP="$(deployTimestamp)"
        if [ -d "$(productionPath)/frontend-live" ]; then
          echo "Backing up current frontend..."
          cp -r $(productionPath)/frontend-live $(backupPath)/$TIMESTAMP/frontend-live-backup
          echo "Frontend backup completed"
        fi
        
        if [ -d "$(productionPath)/backend-live" ]; then
          echo "Backing up current backend..."
          cp -r $(productionPath)/backend-live $(backupPath)/$TIMESTAMP/backend-live-backup
          echo "Backend backup completed"
        fi
      displayName: 'Backup Current Production'

    - script: |
        # Check if PM2 is running and get current status
        if command -v pm2 &> /dev/null; then
          pm2 list
          echo "PM2 status checked"
        else
          echo "PM2 not found, will install during deployment"
        fi
      displayName: 'Check PM2 Status'

- stage: DeployProduction
  displayName: 'Deploy to Production'
  dependsOn: PreDeploy
  condition: succeeded('PreDeploy')
  jobs:
  - job: DeployFrontendProd
    displayName: 'Deploy Frontend to Production'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'frontend'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        # Create frontend production directory
        mkdir -p $(productionPath)/frontend-live
        echo "Created frontend production directory"
      displayName: 'Create Frontend Directory'

    - script: |
        # Extract new frontend build
        echo "Debugging artifact extraction..."
        echo "Artifacts directory contents:"
        ls -la $(System.ArtifactsDirectory)/
        echo "Frontend artifact contents:"
        ls -la $(System.ArtifactsDirectory)/frontend/
        
        # Extract frontend build
        tar -xzf $(System.ArtifactsDirectory)/frontend/frontend_live.tar.gz -C $(productionPath)/frontend-live
        echo "Frontend extracted to $(productionPath)/frontend-live"
      displayName: 'Extract Frontend Build'

    - script: |
        # Install PM2 if not present
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          echo "PM2 installed"
        fi
        
        # Install production dependencies
        cd $(productionPath)/frontend-live
        if [ -f "package-lock.json" ]; then
          npm ci --omit=dev
          echo "Production dependencies installed via npm ci"
        else
          npm install --omit=dev
          echo "Production dependencies installed via npm install"
        fi
      displayName: 'Install Dependencies'

    - script: |
        # Setup environment file for frontend
        cd $(productionPath)/frontend-live
        if [ ! -f ".env.local" ]; then
          echo "Creating frontend .env.local file..."
        echo "# API Configuration" > .env.local
        echo "NEXT_PUBLIC_API_URL=http://localhost:5001" >> .env.local
        echo "NEXT_PUBLIC_FRONTEND_URL=http://localhost:4000" >> .env.local
        echo "" >> .env.local
        echo "# App Configuration" >> .env.local
        echo "NEXT_PUBLIC_APP_NAME=\"AstroFinance\"" >> .env.local
        echo "NEXT_PUBLIC_APP_VERSION=\"1.0.0\"" >> .env.local
        echo "" >> .env.local
        echo "# Environment" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        echo "PORT=4000" >> .env.local
          echo "" >> .env.local
          echo "# Features" >> .env.local
          echo "NEXT_PUBLIC_ENABLE_ANALYTICS=false" >> .env.local
          echo "NEXT_PUBLIC_DEBUG_MODE=false" >> .env.local
          echo "Frontend .env.local file created"
        else
          echo "Frontend .env.local file already exists"
        fi
      displayName: 'Setup Frontend Environment'

    - script: |
        # Restart frontend with PM2
        cd $(productionPath)/frontend-live
        echo "Starting frontend deployment..."
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        
        pm2 delete frontend-live 2>/dev/null || true
        pm2 start npm --name "frontend-live" --cwd $(productionPath)/frontend-live -- start -- --port 4000
        pm2 save
        echo "Frontend restarted with PM2 on port 4000"
        
        # Show PM2 logs for debugging
        echo "PM2 status after frontend start:"
        pm2 list
      displayName: 'Restart Frontend with PM2'

    

  - job: DeployBackendProd
    displayName: 'Deploy Backend to Production'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'backend'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        # Create backend production directory
        mkdir -p $(productionPath)/backend-live
        echo "Created backend production directory"
      displayName: 'Create Backend Directory'

    - script: |
        # Extract new backend build
        echo "Debugging backend artifact extraction..."
        echo "Artifacts directory contents:"
        ls -la $(System.ArtifactsDirectory)/
        echo "Backend artifact contents:"
        ls -la $(System.ArtifactsDirectory)/backend/
        
        # Extract backend build
        tar -xzf $(System.ArtifactsDirectory)/backend/backend_live.tar.gz -C $(productionPath)/backend-live
        echo "Backend extracted to $(productionPath)/backend-live"
      displayName: 'Extract Backend Build'

    - script: |
        # Install PM2 if not present
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          echo "PM2 installed"
        fi
        
        # Install production dependencies
        cd $(productionPath)/backend-live
        if [ -f "package-lock.json" ]; then
          npm ci --omit=dev
          echo "Production dependencies installed via npm ci"
        else
          npm install --omit=dev
          echo "Production dependencies installed via npm install"
        fi
      displayName: 'Install Dependencies'

    - script: |
        # Setup environment file for backend
        cd $(productionPath)/backend-live
        if [ ! -f ".env" ]; then
          echo "Creating backend .env file..."
          echo "# Database" > .env
          echo "DATABASE_URL=\"postgresql://username:password@localhost:5432/astrofinance\"" >> .env
          echo "" >> .env
          echo "# Server" >> .env
          echo "PORT=5001" >> .env
          echo "NODE_ENV=production" >> .env
          echo "" >> .env
          echo "# JWT" >> .env
          echo "JWT_SECRET=\"your-jwt-secret-key-here\"" >> .env
          echo "JWT_EXPIRES_IN=\"24h\"" >> .env
          echo "" >> .env
          echo "# API" >> .env
          echo "API_BASE_URL=\"http://localhost:5001\"" >> .env
          echo "FRONTEND_URL=\"http://localhost:4000\"" >> .env
          echo "" >> .env
          echo "# Email (if needed)" >> .env
          echo "SMTP_HOST=\"\"" >> .env
          echo "SMTP_PORT=\"\"" >> .env
          echo "SMTP_USER=\"\"" >> .env
          echo "SMTP_PASS=\"\"" >> .env
          echo "" >> .env
          echo "# Other services" >> .env
          echo "REDIS_URL=\"redis://localhost:6379\"" >> .env
          echo "Backend .env file created"
        else
          echo "Backend .env file already exists"
        fi
      displayName: 'Setup Backend Environment'

    - script: |
        # Restart backend with PM2
        cd $(productionPath)/backend-live
        echo "Starting backend deployment..."
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Environment file contents:"
        cat .env || echo "No .env file found"
        
        pm2 delete backend-live 2>/dev/null || true
        pm2 start npm --name "backend-live" --cwd $(productionPath)/backend-live -- start
        pm2 save
        echo "Backend restarted with PM2 on port 5001"
        
        # Show PM2 logs for debugging
        echo "PM2 status after backend start:"
        pm2 list
      displayName: 'Restart Backend with PM2'

   