trigger:
  branches:
    include:
      - main
      
  paths:
    include:
      - fe/*
      - be/*

pool:
  name: 'Astro'

variables:
  nodeVersion: '24.x'
  productionPath: '/var/www/astrofinance'
  backupPath: '/var/www/astrofinance/backups'

stages:
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: BuildFrontendJob
    displayName: 'Build Next.js App'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'
    
    - script: |
        cd fe
        npm install
      displayName: 'Install Frontend Dependencies'
    
    - script: |
        cd fe
        npm run type-check
      displayName: 'Run TypeScript Check'
    
    - script: |
        cd fe
        npm run build
      displayName: 'Build Frontend Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'fe'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend_live.tar.gz'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend_live.tar.gz'
        ArtifactName: 'frontend'
        publishLocation: 'Container'

- stage: BuildBackend
  displayName: 'Build Backend'
  jobs:
  - job: BuildBackendJob
    displayName: 'Build Node.js API'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'
    
    - script: |
        cd be
        npm install
      displayName: 'Install Backend Dependencies'

    - script: |
        cd be
        npm run prisma:generate
      displayName: 'Generate Prisma Client'
    
    - script: |
        cd be
        npm run build
      displayName: 'Build Backend Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'be'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend_live.tar.gz'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend_live.tar.gz'
        ArtifactName: 'backend'
        publishLocation: 'Container'

- stage: PreDeploy
  displayName: 'Pre-Deployment Setup'
  dependsOn: 
    - BuildFrontend
    - BuildBackend
  condition: and(succeeded('BuildFrontend'), succeeded('BuildBackend'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: PreDeployJob
    displayName: 'Prepare Production Environment'
    steps:
    - script: |
        # Ensure production directories exist with proper permissions
        sudo mkdir -p $(productionPath)
        sudo mkdir -p $(backupPath)
        sudo chown -R $(whoami):$(whoami) $(productionPath)
        sudo chown -R $(whoami):$(whoami) $(backupPath)
        sudo chmod -R 755 $(productionPath)
        sudo chmod -R 755 $(backupPath)
        echo "Production and backup directories prepared"
      displayName: 'Setup Base Directories'

    - script: |
        # Create backup directories with timestamp
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        mkdir -p $(backupPath)/$TIMESTAMP
        echo "Created backup directory: $(backupPath)/$TIMESTAMP"
        echo "##vso[task.setvariable variable=deployTimestamp]$TIMESTAMP"
      displayName: 'Create Backup Directory'

    - script: |
        # Backup current production if it exists
        TIMESTAMP="$(deployTimestamp)"
        if [ -d "$(productionPath)/frontend-live" ]; then
          echo "Backing up current frontend..."
          cp -r $(productionPath)/frontend-live $(backupPath)/$TIMESTAMP/frontend-live-backup
          echo "Frontend backup completed"
        fi
        
        if [ -d "$(productionPath)/backend-live" ]; then
          echo "Backing up current backend..."
          cp -r $(productionPath)/backend-live $(backupPath)/$TIMESTAMP/backend-live-backup
          echo "Backend backup completed"
        fi
      displayName: 'Backup Current Production'

    - script: |
        # Check if PM2 is running and get current status
        if command -v pm2 &> /dev/null; then
          pm2 list
          echo "PM2 status checked"
        else
          echo "PM2 not found, will install during deployment"
        fi
      displayName: 'Check PM2 Status'

- stage: DeployProduction
  displayName: 'Deploy to Production'
  dependsOn: PreDeploy
  condition: succeeded('PreDeploy')
  jobs:
  - job: DeployFrontendProd
    displayName: 'Deploy Frontend to Production'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'frontend'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        # Create frontend production directory
        mkdir -p $(productionPath)/frontend-live
        echo "Created frontend production directory"
      displayName: 'Create Frontend Directory'

    - script: |
        # Extract new frontend build
        echo "Debugging artifact extraction..."
        echo "Artifacts directory contents:"
        ls -la $(System.ArtifactsDirectory)/
        echo "Frontend artifact contents:"
        ls -la $(System.ArtifactsDirectory)/frontend/
        
        tar -xzf $(System.ArtifactsDirectory)/frontend/frontend_live.tar.gz -C $(productionPath)/frontend-live
        echo "Frontend extracted to $(productionPath)/frontend-live"
      displayName: 'Extract Frontend Build'

    - script: |
        # Install PM2 if not present
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          echo "PM2 installed"
        fi
        
        # Install production dependencies
        cd $(productionPath)/frontend-live
        if [ -f "package-lock.json" ]; then
          npm ci --omit=dev
          echo "Production dependencies installed via npm ci"
        else
          npm install --omit=dev
          echo "Production dependencies installed via npm install"
        fi
      displayName: 'Install Dependencies'

    - script: |
        # Setup environment file for frontend
        cd $(productionPath)/frontend-live
        if [ ! -f ".env.local" ]; then
          echo "Creating frontend .env.local file..."
        echo "# API Configuration" > .env.local
        echo "NEXT_PUBLIC_API_URL=http://localhost:5001" >> .env.local
        echo "NEXT_PUBLIC_FRONTEND_URL=http://localhost:4000" >> .env.local
        echo "" >> .env.local
        echo "# App Configuration" >> .env.local
        echo "NEXT_PUBLIC_APP_NAME=\"AstroFinance\"" >> .env.local
        echo "NEXT_PUBLIC_APP_VERSION=\"1.0.0\"" >> .env.local
        echo "" >> .env.local
        echo "# Environment" >> .env.local
        echo "NODE_ENV=production" >> .env.local
        echo "PORT=4000" >> .env.local
          echo "" >> .env.local
          echo "# Features" >> .env.local
          echo "NEXT_PUBLIC_ENABLE_ANALYTICS=false" >> .env.local
          echo "NEXT_PUBLIC_DEBUG_MODE=false" >> .env.local
          echo "Frontend .env.local file created"
        else
          echo "Frontend .env.local file already exists"
        fi
      displayName: 'Setup Frontend Environment'

    - script: |
        # Restart frontend with PM2
        cd $(productionPath)/frontend-live
        echo "Starting frontend deployment..."
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        
        pm2 delete frontend-live 2>/dev/null || true
        pm2 start npm --name "frontend-live" -- start -- --port 4000
        pm2 save
        echo "Frontend restarted with PM2 on port 4000"
        
        # Show PM2 logs for debugging
        echo "PM2 status after frontend start:"
        pm2 list
      displayName: 'Restart Frontend with PM2'

    - script: |
        # Health check for frontend
        echo "Starting frontend health check..."
        sleep 10
        
        echo "PM2 status:"
        pm2 list
        
        echo "Frontend logs (last 20 lines):"
        pm2 logs frontend-live --lines 20 || echo "No logs available"
        
        if pm2 list | grep -q "frontend-live.*online"; then
          echo "✅ Frontend health check passed - Service is online"
          
          # Test if port 4000 is responding
          if curl -f http://localhost:4000 > /dev/null 2>&1; then
            echo "✅ Frontend port 4000 is responding"
          else
            echo "⚠️ Frontend port 4000 is not responding, but PM2 shows online"
          fi
        else
          echo "❌ Frontend health check failed - Service is not online"
          echo "PM2 error logs:"
          pm2 logs frontend-live --err --lines 10 || echo "No error logs available"
          exit 1
        fi
      displayName: 'Frontend Health Check'

  - job: DeployBackendProd
    displayName: 'Deploy Backend to Production'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'backend'
        downloadPath: '$(System.ArtifactsDirectory)'

    - script: |
        # Create backend production directory
        mkdir -p $(productionPath)/backend-live
        echo "Created backend production directory"
      displayName: 'Create Backend Directory'

    - script: |
        # Extract new backend build
        echo "Debugging backend artifact extraction..."
        echo "Artifacts directory contents:"
        ls -la $(System.ArtifactsDirectory)/
        echo "Backend artifact contents:"
        ls -la $(System.ArtifactsDirectory)/backend/
        
        tar -xzf $(System.ArtifactsDirectory)/backend/backend_live.tar.gz -C $(productionPath)/backend-live
        echo "Backend extracted to $(productionPath)/backend-live"
      displayName: 'Extract Backend Build'

    - script: |
        # Install PM2 if not present
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          echo "PM2 installed"
        fi
        
        # Install production dependencies
        cd $(productionPath)/backend-live
        if [ -f "package-lock.json" ]; then
          npm ci --omit=dev
          echo "Production dependencies installed via npm ci"
        else
          npm install --omit=dev
          echo "Production dependencies installed via npm install"
        fi
      displayName: 'Install Dependencies'

    - script: |
        # Setup environment file for backend
        cd $(productionPath)/backend-live
        if [ ! -f ".env" ]; then
          echo "Creating backend .env file..."
          echo "# Database" > .env
          echo "DATABASE_URL=\"postgresql://username:password@localhost:5432/astrofinance\"" >> .env
          echo "" >> .env
          echo "# Server" >> .env
          echo "PORT=5001" >> .env
          echo "NODE_ENV=production" >> .env
          echo "" >> .env
          echo "# JWT" >> .env
          echo "JWT_SECRET=\"your-jwt-secret-key-here\"" >> .env
          echo "JWT_EXPIRES_IN=\"24h\"" >> .env
          echo "" >> .env
          echo "# API" >> .env
          echo "API_BASE_URL=\"http://localhost:5001\"" >> .env
          echo "FRONTEND_URL=\"http://localhost:4000\"" >> .env
          echo "" >> .env
          echo "# Email (if needed)" >> .env
          echo "SMTP_HOST=\"\"" >> .env
          echo "SMTP_PORT=\"\"" >> .env
          echo "SMTP_USER=\"\"" >> .env
          echo "SMTP_PASS=\"\"" >> .env
          echo "" >> .env
          echo "# Other services" >> .env
          echo "REDIS_URL=\"redis://localhost:6379\"" >> .env
          echo "Backend .env file created"
        else
          echo "Backend .env file already exists"
        fi
      displayName: 'Setup Backend Environment'

    - script: |
        # Restart backend with PM2
        cd $(productionPath)/backend-live
        echo "Starting backend deployment..."
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Environment file contents:"
        cat .env || echo "No .env file found"
        
        pm2 delete backend-live 2>/dev/null || true
        pm2 start npm --name "backend-live" -- start
        pm2 save
        echo "Backend restarted with PM2 on port 5001"
        
        # Show PM2 logs for debugging
        echo "PM2 status after backend start:"
        pm2 list
      displayName: 'Restart Backend with PM2'

   

- stage: PostDeploy
  displayName: 'Post-Deployment Verification'
  dependsOn: DeployProduction
  condition: succeeded('DeployProduction')
  jobs:
  - job: PostDeployJob
    displayName: 'Verify Production Deployment'
    steps:
    - script: |
        # Final PM2 status check with detailed debugging
        echo "=== FINAL DEPLOYMENT STATUS ==="
        echo "Timestamp: $(date)"
        echo "Production Path: $(productionPath)"
        echo "Backup Path: $(backupPath)/$(deployTimestamp)"
        echo ""
        
        echo "=== PM2 STATUS ==="
        pm2 list
        echo ""
        
        echo "=== FRONTEND DEBUG INFO ==="
        echo "Frontend directory: $(productionPath)/frontend-live"
        if [ -d "$(productionPath)/frontend-live" ]; then
          echo "Frontend files:"
          ls -la $(productionPath)/frontend-live/ | head -10
          echo ""
          echo "Frontend .env.local:"
          cat $(productionPath)/frontend-live/.env.local 2>/dev/null || echo "No .env.local found"
        else
          echo "Frontend directory not found!"
        fi
        echo ""
        
        echo "=== BACKEND DEBUG INFO ==="
        echo "Backend directory: $(productionPath)/backend-live"
        if [ -d "$(productionPath)/backend-live" ]; then
          echo "Backend files:"
          ls -la $(productionPath)/backend-live/ | head -10
          echo ""
          echo "Backend .env:"
          cat $(productionPath)/backend-live/.env 2>/dev/null || echo "No .env found"
        else
          echo "Backend directory not found!"
        fi
        echo ""
        
        echo "=== PORT CHECKS ==="
        echo "Checking port 4000 (frontend):"
        netstat -tlnp | grep :4000 || echo "Port 4000 not listening"
        echo ""
        echo "Checking port 5001 (backend):"
        netstat -tlnp | grep :5001 || echo "Port 5001 not listening"
        echo ""
        
        echo "=== RECENT LOGS ==="
        echo "Frontend logs (last 10 lines):"
        pm2 logs frontend-live --lines 10 2>/dev/null || echo "No frontend logs"
        echo ""
        echo "Backend logs (last 10 lines):"
        pm2 logs backend-live --lines 10 2>/dev/null || echo "No backend logs"
        echo ""
        
        echo "Final PM2 status check completed"
      displayName: 'Final PM2 Status Check'

    - script: |
        # Clean up old backups (keep last 5)
        cd $(backupPath)
        ls -t | tail -n +6 | xargs -r rm -rf
        echo "Old backups cleaned up"
      displayName: 'Cleanup Old Backups'

    - script: |
        # Log deployment success
        echo "Production deployment completed successfully at $(date)"
        echo "Deployment timestamp: $(deployTimestamp)"
        echo "Frontend: $(productionPath)/frontend-live"
        echo "Backend: $(productionPath)/backend-live"
        echo "Backup: $(backupPath)/$(deployTimestamp)"
      displayName: 'Log Deployment Success'

- stage: Rollback
  displayName: 'Rollback on Failure'
  dependsOn: 
    - DeployProduction
    - PostDeploy
  condition: or(failed('DeployProduction'), failed('PostDeploy'))
  jobs:
  - job: RollbackJob
    displayName: 'Rollback to Previous Version'
    steps:
    - script: |
        echo "Deployment failed, initiating rollback..."
        echo "Rolling back to backup: $(backupPath)/$(deployTimestamp)"
      displayName: 'Start Rollback Process'

    - script: |
        # Stop current services
        pm2 delete frontend-live 2>/dev/null || true
        pm2 delete backend-live 2>/dev/null || true
        echo "Current services stopped"
      displayName: 'Stop Current Services'

    - script: |
        # Restore frontend from backup
        if [ -d "$(backupPath)/$(deployTimestamp)/frontend-live-backup" ]; then
          rm -rf $(productionPath)/frontend-live
          cp -r $(backupPath)/$(deployTimestamp)/frontend-live-backup $(productionPath)/frontend-live
          echo "Frontend restored from backup"
        else
          echo "No frontend backup found"
        fi
      displayName: 'Restore Frontend'

    - script: |
        # Restore backend from backup
        if [ -d "$(backupPath)/$(deployTimestamp)/backend-live-backup" ]; then
          rm -rf $(productionPath)/backend-live
          cp -r $(backupPath)/$(deployTimestamp)/backend-live-backup $(productionPath)/backend-live
          echo "Backend restored from backup"
        else
          echo "No backend backup found"
        fi
      displayName: 'Restore Backend'

    - script: |
        # Restart services
        cd $(productionPath)/frontend-live
        pm2 start npm --name "frontend-live" -- start 2>/dev/null || true
        
        cd $(productionPath)/backend-live
        pm2 start npm --name "backend-live" -- start 2>/dev/null || true
        
        pm2 save
        echo "Services restarted after rollback"
      displayName: 'Restart Services After Rollback'

    - script: |
        # Verify rollback
        sleep 10
        pm2 list
        echo "Rollback completed. Check service status above."
      displayName: 'Verify Rollback'
