parameters:
  - name: environment
    type: string
    default: 'development'
  - name: artifactName
    type: string
    default: 'app'
  - name: appType
    type: string
    default: 'webApp'
  - name: appName
    type: string
    default: ''
  - name: startUpCommand
    type: string
    default: ''

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: '${{ parameters.artifactName }}'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Subscription'
    appType: '${{ parameters.appType }}'
    appName: '${{ parameters.appName }}'
    package: '$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/${{ parameters.artifactName }}.zip'
    deploymentMethod: 'auto'
    ${{ if ne(parameters.startUpCommand, '') }}:
      startUpCommand: '${{ parameters.startUpCommand }}'